services:
  # Web service
  - type: web
    name: chad-battles
    env: python
    buildCommand: pip install -r requirements_minimal.txt && python setup_minimal.py --non-interactive
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chad-battles-db
          property: connectionString
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false

  # Twitter bot cron job - commenting out for initial deployment
  # - type: cron
  #   name: twitter-bot
  #   env: python
  #   schedule: "*/5 * * * *"
  #   buildCommand: pip install -r requirements_minimal.txt
  #   startCommand: python twitter_bot.py
  #   envVars:
  #     - key: FLASK_APP
  #       value: app
  #     - key: FLASK_ENV
  #       value: production
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: chad-battles-db
  #         property: connectionString
  #     - key: TWITTER_API_KEY
  #       sync: false
  #     - key: TWITTER_API_SECRET
  #       sync: false
  #     - key: TWITTER_ACCESS_TOKEN
  #       sync: false
  #     - key: TWITTER_ACCESS_TOKEN_SECRET
  #       sync: false
  #     - key: TWITTER_BEARER_TOKEN
  #       sync: false

# Database
databases:
  - name: chad-battles-db
    plan: free 