services:
  # Web service
  - type: web
    name: chad-battles
    env: python
    buildCommand: pip install --no-cache-dir -r requirements_deployment.txt
    startCommand: gunicorn 'app:create_app("production")' --bind=0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chad-battles-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    preDeployCommand: python setup_render_db.py
    # Add health check
    healthCheckPath: /health
    # Auto-restart on crash
    autoDeploy: true
    # Zero-downtime deployments
    numInstances: 1
    # Enable more logging for debugging
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chad-battles-db
          property: connectionString
      - key: ENABLE_BLOCKCHAIN
        value: false
      - key: ENABLE_TWITTER_BOT
        value: true
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: LOG_LEVEL
        value: DEBUG

  # Twitter bot cron job
  - type: cron
    name: twitter-bot
    env: python
    schedule: "*/5 * * * *"
    buildCommand: >
      pip install --no-cache-dir -r requirements_deployment.txt
    startCommand: python twitter_bot.py
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chad-battles-db
          property: connectionString
      - key: ENABLE_BLOCKCHAIN
        value: false
      - key: ENABLE_TWITTER_BOT
        value: true
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false

# Database
databases:
  - name: chad-battles-db
    plan: starter
    ipAllowList: [] 